FROM busybox:latest
MAINTAINER Richard Robinson <rrobinso@redhat.com>
LABLE io.openshift.s2i.scripts-url https://github.com/rhopenshift-online/origin-test/tree/master/examples/hello-openshift/
USER 1
