FROM busybox:latest
MAINTAINER Richard Robinson <rrobinso@redhat.com>
LABEL io.openshift.s2i.scripts-url https://github.com/rhopenshift-online/origin-test/tree/master/examples/hello-openshift/.s2i/bin
USER 1
